Instala as Bibliotecas

In [ ]:
pip install pandas

In [ ]:
pip install sqlalchemy

In [ ]:
pip install psycopg2

Importar as Bibliotecas

In [1]:
import pandas as pd
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.min_rows", 20)

from sqlalchemy import create_engine

from datetime import datetime

import time

/tmp/ipykernel_59566/181854908.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

Definir função para buscar os Dados

In [2]:
def busca_titulos_tesouro_direto():
    url = 'https://www.tesourotransparente.gov.br/ckan/dataset/df56aa42-484a-4a59-8184-7676580c81e3/resource/796d2059-14e9-44e3-80c9-2d9e30b405c1/download/PrecoTaxaTesouroDireto.csv'
    df = pd.read_csv(url, sep=';', decimal=',')
    df['Data_Vencimento'] = pd.to_datetime(df['Data Vencimento'], dayfirst=True)
    df['Data_Base'] = pd.to_datetime(df['Data Base'], dayfirst=True)
    multi_indice = pd.MultiIndex.from_frame(df.iloc[:,:3])
    df = df.set_index(multi_indice).iloc[:, 3:]
    return df

Busca os títulos do Tesouro Direto

In [3]:
titulos = busca_titulos_tesouro_direto()

In [4]:
titulos

                                                                   Taxa Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024               9.76
                                       01/01/2033      13/03/2024              10.68
                                       01/01/2035      13/03/2024              10.77
                                       01/01/2027      13/03/2024               9.91
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024               5.84
                                       15/12/2064      13/03/2024               5.79
                                       15/12/2054      13/03/2024               5.75
                                       15/12/2069      13/03/2024               5.80
                                       15/12/2079      13/03/2024               5.84
                                       15/12/2049      13/03/2024               5.72
...                                                                              ...
Tesouro Selic                          18/06/2008      21/01/2005               0.28
                                       18/03/2009      21/01/2005               0.32
Tesouro Prefixado                      01/04/2005      21/01/2005              18.74
                                       01/07/2005      21/01/2005              19.07
                                       01/10/2005      21/01/2005              19.06
                                       01/01/2006      21/01/2005              18.85
                                       01/07/2006      21/01/2005              18.51
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005               8.83
                                       15/05/2009      21/01/2005               8.84
                                       15/05/2045      21/01/2005               9.03

                                                                   Taxa Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024              9.88
                                       01/01/2033      13/03/2024             10.80
                                       01/01/2035      13/03/2024             10.89
                                       01/01/2027      13/03/2024             10.03
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024              5.96
                                       15/12/2064      13/03/2024              5.91
                                       15/12/2054      13/03/2024              5.87
                                       15/12/2069      13/03/2024              5.92
                                       15/12/2079      13/03/2024              5.96
                                       15/12/2049      13/03/2024              5.84
...                                                                             ...
Tesouro Selic                          18/06/2008      21/01/2005              0.36
                                       18/03/2009      21/01/2005              0.40
Tesouro Prefixado                      01/04/2005      21/01/2005             18.78
                                       01/07/2005      21/01/2005             19.11
                                       01/10/2005      21/01/2005             19.12
                                       01/01/2006      21/01/2005             18.91
                                       01/07/2006      21/01/2005             18.59
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005              8.85
                                       15/05/2009      21/01/2005              8.88
                                       15/05/2045      21/01/2005              9.13

                                                                   PU Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024          1020.50
                                       01/01/2033      13/03/2024           985.23
                                       01/01/2035      13/03/2024           975.99
                                       01/01/2027      13/03/2024          1021.85
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024           254.74
                                       15/12/2064      13/03/2024           798.11
                                       15/12/2054      13/03/2024          1406.35
                                       15/12/2069      13/03/2024           601.44
                                       15/12/2079      13/03/2024           337.75
                                       15/12/2049      13/03/2024          1864.12
...                                                                            ...
Tesouro Selic                          18/06/2008      21/01/2005          2163.52
                                       18/03/2009      21/01/2005          2155.39
Tesouro Prefixado                      01/04/2005      21/01/2005           969.13
                                       01/07/2005      21/01/2005           927.28
                                       01/10/2005      21/01/2005           886.51
                                       01/01/2006      21/01/2005           850.67
                                       01/07/2006      21/01/2005           784.57
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005          1470.03
                                       15/05/2009      21/01/2005          1363.82
                                       15/05/2045      21/01/2005          1032.04

                                                                   PU Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024         1019.24
                                       01/01/2033      13/03/2024          978.55
                                       01/01/2035      13/03/2024          968.60
                                       01/01/2027      13/03/2024         1018.72
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024          240.95
                                       15/12/2064      13/03/2024          772.09
                                       15/12/2054      13/03/2024         1375.89
                                       15/12/2069      13/03/2024          578.57
                                       15/12/2079      13/03/2024          321.28
                                       15/12/2049      13/03/2024         1834.03
...                                                                           ...
Tesouro Selic                          18/06/2008      21/01/2005         2157.72
                                       18/03/2009      21/01/2005         2148.31
Tesouro Prefixado                      01/04/2005      21/01/2005          969.07
                                       01/07/2005      21/01/2005          927.14
                                       01/10/2005      21/01/2005          886.20
                                       01/01/2006      21/01/2005          850.27
                                       01/07/2006      21/01/2005          783.82
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005         1469.64
                                       15/05/2009      21/01/2005         1361.93
                                       15/05/2045      21/01/2005         1021.10

                                                                   PU Base Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024        1019.24
                                       01/01/2033      13/03/2024         978.55
                                       01/01/2035      13/03/2024         968.60
                                       01/01/2027      13/03/2024        1018.72
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024         240.95
                                       15/12/2064      13/03/2024         772.09
                                       15/12/2054      13/03/2024        1375.89
                                       15/12/2069      13/03/2024         578.57
                                       15/12/2079      13/03/2024         321.28
                                       15/12/2049      13/03/2024        1834.03
...                                                                          ...
Tesouro Selic                          18/06/2008      21/01/2005        2156.25
                                       18/03/2009      21/01/2005        2146.85
Tesouro Prefixado                      01/04/2005      21/01/2005         968.41
                                       01/07/2005      21/01/2005         926.50
                                       01/10/2005      21/01/2005         885.59
                                       01/01/2006      21/01/2005         849.68
                                       01/07/2006      21/01/2005         783.29
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005        1468.21
                                       15/05/2009      21/01/2005        1360.61
                                       15/05/2045      21/01/2005        1020.09

                                                                  Data_Vencimento  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024      2025-01-01
                                       01/01/2033      13/03/2024      2033-01-01
                                       01/01/2035      13/03/2024      2035-01-01
                                       01/01/2027      13/03/2024      2027-01-01
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024      2084-12-15
                                       15/12/2064      13/03/2024      2064-12-15
                                       15/12/2054      13/03/2024      2054-12-15
                                       15/12/2069      13/03/2024      2069-12-15
                                       15/12/2079      13/03/2024      2079-12-15
                                       15/12/2049      13/03/2024      2049-12-15
...                                                                           ...
Tesouro Selic                          18/06/2008      21/01/2005      2008-06-18
                                       18/03/2009      21/01/2005      2009-03-18
Tesouro Prefixado                      01/04/2005      21/01/2005      2005-04-01
                                       01/07/2005      21/01/2005      2005-07-01
                                       01/10/2005      21/01/2005      2005-10-01
                                       01/01/2006      21/01/2005      2006-01-01
                                       01/07/2006      21/01/2005      2006-07-01
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005      2006-08-15
                                       15/05/2009      21/01/2005      2009-05-15
                                       15/05/2045      21/01/2005      2045-05-15

                                                                   Data_Base
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado com Juros Semestrais 01/01/2025      13/03/2024 2024-03-13
                                       01/01/2033      13/03/2024 2024-03-13
                                       01/01/2035      13/03/2024 2024-03-13
                                       01/01/2027      13/03/2024 2024-03-13
Tesouro Renda+ Aposentadoria Extra     15/12/2084      13/03/2024 2024-03-13
                                       15/12/2064      13/03/2024 2024-03-13
                                       15/12/2054      13/03/2024 2024-03-13
                                       15/12/2069      13/03/2024 2024-03-13
                                       15/12/2079      13/03/2024 2024-03-13
                                       15/12/2049      13/03/2024 2024-03-13
...                                                                      ...
Tesouro Selic                          18/06/2008      21/01/2005 2005-01-21
                                       18/03/2009      21/01/2005 2005-01-21
Tesouro Prefixado                      01/04/2005      21/01/2005 2005-01-21
                                       01/07/2005      21/01/2005 2005-01-21
                                       01/10/2005      21/01/2005 2005-01-21
                                       01/01/2006      21/01/2005 2005-01-21
                                       01/07/2006      21/01/2005 2005-01-21
Tesouro IPCA+ com Juros Semestrais     15/08/2006      21/01/2005 2005-01-21
                                       15/05/2009      21/01/2005 2005-01-21
                                       15/05/2045      21/01/2005 2005-01-21

[141001 rows x 7 columns]

Busca somente os Préfixados

In [5]:
prefixado = titulos.loc[('Tesouro Prefixado')]
prefixado['Tipo'] = "PRE-FIXADOS"

/tmp/ipykernel_59566/2914005242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado['Tipo'] = "PRE-FIXADOS"

In [6]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
01/01/2025      12/03/2024               9.72              9.84
01/01/2031      12/03/2024              10.74             10.86
01/07/2024      12/03/2024              10.26             10.38
01/01/2029      12/03/2024              10.47             10.59
01/01/2026      12/03/2024               9.69              9.81
01/01/2027      12/03/2024               9.94             10.06
                11/03/2024              10.04             10.16
01/01/2026      11/03/2024               9.78              9.90
01/01/2025      11/03/2024               9.77              9.89
01/01/2031      11/03/2024              10.84             10.96
...                                       ...               ...
01/04/2005      24/01/2005              18.76             18.80
01/07/2005      24/01/2005              19.15             19.19
01/10/2005      24/01/2005              19.15             19.21
01/01/2006      24/01/2005              18.97             19.03
01/07/2006      24/01/2005              18.54             18.62
01/04/2005      21/01/2005              18.74             18.78
01/07/2005      21/01/2005              19.07             19.11
01/10/2005      21/01/2005              19.06             19.12
01/01/2006      21/01/2005              18.85             18.91
01/07/2006      21/01/2005              18.51             18.59

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
01/01/2025      12/03/2024           927.65          926.49         926.49
01/01/2031      12/03/2024           501.46          497.60         497.60
01/07/2024      12/03/2024           971.34          970.65         970.65
01/01/2029      12/03/2024           621.42          617.96         617.96
01/01/2026      12/03/2024           845.89          843.91         843.91
01/01/2027      12/03/2024           767.11          764.48         764.48
                11/03/2024           764.87          762.25         762.25
01/01/2026      11/03/2024           844.32          842.34         842.34
01/01/2025      11/03/2024           926.97          925.80         925.80
01/01/2031      11/03/2024           498.20          494.36         494.36
...                                     ...             ...            ...
01/04/2005      24/01/2005           969.76          969.70         969.04
01/07/2005      24/01/2005           927.65          927.52         926.87
01/10/2005      24/01/2005           886.66          886.36         885.74
01/01/2006      24/01/2005           850.45          850.05         849.46
01/07/2006      24/01/2005           784.82          784.06         783.53
01/04/2005      21/01/2005           969.13          969.07         968.41
01/07/2005      21/01/2005           927.28          927.14         926.50
01/10/2005      21/01/2005           886.51          886.20         885.59
01/01/2006      21/01/2005           850.67          850.27         849.68
01/07/2006      21/01/2005           784.57          783.82         783.29

                           Data_Vencimento  Data_Base         Tipo
Data Vencimento Data Base
01/01/2025      12/03/2024      2025-01-01 2024-03-12  PRE-FIXADOS
01/01/2031      12/03/2024      2031-01-01 2024-03-12  PRE-FIXADOS
01/07/2024      12/03/2024      2024-07-01 2024-03-12  PRE-FIXADOS
01/01/2029      12/03/2024      2029-01-01 2024-03-12  PRE-FIXADOS
01/01/2026      12/03/2024      2026-01-01 2024-03-12  PRE-FIXADOS
01/01/2027      12/03/2024      2027-01-01 2024-03-12  PRE-FIXADOS
                11/03/2024      2027-01-01 2024-03-11  PRE-FIXADOS
01/01/2026      11/03/2024      2026-01-01 2024-03-11  PRE-FIXADOS
01/01/2025      11/03/2024      2025-01-01 2024-03-11  PRE-FIXADOS
01/01/2031      11/03/2024      2031-01-01 2024-03-11  PRE-FIXADOS
...                                    ...        ...          ...
01/04/2005      24/01/2005      2005-04-01 2005-01-24  PRE-FIXADOS
01/07/2005      24/01/2005      2005-07-01 2005-01-24  PRE-FIXADOS
01/10/2005      24/01/2005      2005-10-01 2005-01-24  PRE-FIXADOS
01/01/2006      24/01/2005      2006-01-01 2005-01-24  PRE-FIXADOS
01/07/2006      24/01/2005      2006-07-01 2005-01-24  PRE-FIXADOS
01/04/2005      21/01/2005      2005-04-01 2005-01-21  PRE-FIXADOS
01/07/2005      21/01/2005      2005-07-01 2005-01-21  PRE-FIXADOS
01/10/2005      21/01/2005      2005-10-01 2005-01-21  PRE-FIXADOS
01/01/2006      21/01/2005      2006-01-01 2005-01-21  PRE-FIXADOS
01/07/2006      21/01/2005      2006-07-01 2005-01-21  PRE-FIXADOS

[24767 rows x 8 columns]

In [7]:
for i, row in prefixado.iterrows():
    ifor_val = datetime.now()
    prefixado.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

/tmp/ipykernel_59566/19975595.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado.at[i,'dt_update'] = ifor_val

In [8]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
01/01/2025      12/03/2024               9.72              9.84
01/01/2031      12/03/2024              10.74             10.86
01/07/2024      12/03/2024              10.26             10.38
01/01/2029      12/03/2024              10.47             10.59
01/01/2026      12/03/2024               9.69              9.81
01/01/2027      12/03/2024               9.94             10.06
                11/03/2024              10.04             10.16
01/01/2026      11/03/2024               9.78              9.90
01/01/2025      11/03/2024               9.77              9.89
01/01/2031      11/03/2024              10.84             10.96
...                                       ...               ...
01/04/2005      24/01/2005              18.76             18.80
01/07/2005      24/01/2005              19.15             19.19
01/10/2005      24/01/2005              19.15             19.21
01/01/2006      24/01/2005              18.97             19.03
01/07/2006      24/01/2005              18.54             18.62
01/04/2005      21/01/2005              18.74             18.78
01/07/2005      21/01/2005              19.07             19.11
01/10/2005      21/01/2005              19.06             19.12
01/01/2006      21/01/2005              18.85             18.91
01/07/2006      21/01/2005              18.51             18.59

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
01/01/2025      12/03/2024           927.65          926.49         926.49
01/01/2031      12/03/2024           501.46          497.60         497.60
01/07/2024      12/03/2024           971.34          970.65         970.65
01/01/2029      12/03/2024           621.42          617.96         617.96
01/01/2026      12/03/2024           845.89          843.91         843.91
01/01/2027      12/03/2024           767.11          764.48         764.48
                11/03/2024           764.87          762.25         762.25
01/01/2026      11/03/2024           844.32          842.34         842.34
01/01/2025      11/03/2024           926.97          925.80         925.80
01/01/2031      11/03/2024           498.20          494.36         494.36
...                                     ...             ...            ...
01/04/2005      24/01/2005           969.76          969.70         969.04
01/07/2005      24/01/2005           927.65          927.52         926.87
01/10/2005      24/01/2005           886.66          886.36         885.74
01/01/2006      24/01/2005           850.45          850.05         849.46
01/07/2006      24/01/2005           784.82          784.06         783.53
01/04/2005      21/01/2005           969.13          969.07         968.41
01/07/2005      21/01/2005           927.28          927.14         926.50
01/10/2005      21/01/2005           886.51          886.20         885.59
01/01/2006      21/01/2005           850.67          850.27         849.68
01/07/2006      21/01/2005           784.57          783.82         783.29

                           Data_Vencimento  Data_Base         Tipo  \
Data Vencimento Data Base
01/01/2025      12/03/2024      2025-01-01 2024-03-12  PRE-FIXADOS
01/01/2031      12/03/2024      2031-01-01 2024-03-12  PRE-FIXADOS
01/07/2024      12/03/2024      2024-07-01 2024-03-12  PRE-FIXADOS
01/01/2029      12/03/2024      2029-01-01 2024-03-12  PRE-FIXADOS
01/01/2026      12/03/2024      2026-01-01 2024-03-12  PRE-FIXADOS
01/01/2027      12/03/2024      2027-01-01 2024-03-12  PRE-FIXADOS
                11/03/2024      2027-01-01 2024-03-11  PRE-FIXADOS
01/01/2026      11/03/2024      2026-01-01 2024-03-11  PRE-FIXADOS
01/01/2025      11/03/2024      2025-01-01 2024-03-11  PRE-FIXADOS
01/01/2031      11/03/2024      2031-01-01 2024-03-11  PRE-FIXADOS
...                                    ...        ...          ...
01/04/2005      24/01/2005      2005-04-01 2005-01-24  PRE-FIXADOS
01/07/2005      24/01/2005      2005-07-01 2005-01-24  PRE-FIXADOS
01/10/2005      24/01/2005      2005-10-01 2005-01-24  PRE-FIXADOS
01/01/2006      24/01/2005      2006-01-01 2005-01-24  PRE-FIXADOS
01/07/2006      24/01/2005      2006-07-01 2005-01-24  PRE-FIXADOS
01/04/2005      21/01/2005      2005-04-01 2005-01-21  PRE-FIXADOS
01/07/2005      21/01/2005      2005-07-01 2005-01-21  PRE-FIXADOS
01/10/2005      21/01/2005      2005-10-01 2005-01-21  PRE-FIXADOS
01/01/2006      21/01/2005      2006-01-01 2005-01-21  PRE-FIXADOS
01/07/2006      21/01/2005      2006-07-01 2005-01-21  PRE-FIXADOS

                                            dt_update
Data Vencimento Data Base
01/01/2025      12/03/2024 2024-04-02 21:26:24.492103
01/01/2031      12/03/2024 2024-04-02 21:26:24.500220
01/07/2024      12/03/2024 2024-04-02 21:26:24.502474
01/01/2029      12/03/2024 2024-04-02 21:26:24.503236
01/01/2026      12/03/2024 2024-04-02 21:26:24.504064
01/01/2027      12/03/2024 2024-04-02 21:26:24.504799
                11/03/2024 2024-04-02 21:26:24.505400
01/01/2026      11/03/2024 2024-04-02 21:26:24.505879
01/01/2025      11/03/2024 2024-04-02 21:26:24.506646
01/01/2031      11/03/2024 2024-04-02 21:26:24.507206
...                                               ...
01/04/2005      24/01/2005 2024-04-02 21:26:33.961311
01/07/2005      24/01/2005 2024-04-02 21:26:33.961608
01/10/2005      24/01/2005 2024-04-02 21:26:33.961965
01/01/2006      24/01/2005 2024-04-02 21:26:33.962333
01/07/2006      24/01/2005 2024-04-02 21:26:33.962630
01/04/2005      21/01/2005 2024-04-02 21:26:33.962989
01/07/2005      21/01/2005 2024-04-02 21:26:33.963437
01/10/2005      21/01/2005 2024-04-02 21:26:33.964239
01/01/2006      21/01/2005 2024-04-02 21:26:33.964831
01/07/2006      21/01/2005 2024-04-02 21:26:33.965329

[24767 rows x 9 columns]

Busca os IPCAs

In [9]:
ipca = titulos.loc[('Tesouro IPCA+')]
ipca['Tipo'] = "IPCA"

/tmp/ipykernel_59566/3738600803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca['Tipo'] = "IPCA"

In [10]:
for i, row in ipca.iterrows():
    ifor_val = datetime.now()
    ipca.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

/tmp/ipykernel_59566/967398317.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca.at[i,'dt_update'] = ifor_val

In [11]:
ipca

,,Taxa Compra Manha,Taxa Venda Manha,PU Compra Manha,PU Venda Manha,PU Base Manha,Data_Vencimento,Data_Base,Tipo,dt_update
Data Vencimento,Data Base,,,,,,,,,
15/08/2024,12/03/2024,7.68,7.80,4112.61,4108.25,4108.25,2024-08-15,2024-03-12,IPCA,2024-04-02 21:26:34.045149
15/08/2026,12/03/2024,5.58,5.70,3721.46,3709.35,3709.35,2026-08-15,2024-03-12,IPCA,2024-04-02 21:26:34.050148
15/05/2045,12/03/2024,5.77,5.89,1303.22,1271.83,1271.83,2045-05-15,2024-03-12,IPCA,2024-04-02 21:26:34.051062
15/05/2029,12/03/2024,5.55,5.67,3216.18,3195.85,3195.85,2029-05-15,2024-03-12,IPCA,2024-04-02 21:26:34.051580
15/05/2035,12/03/2024,5.65,5.77,2305.51,2275.47,2275.47,2035-05-15,2024-03-12,IPCA,2024-04-02 21:26:34.052039
15/08/2026,11/03/2024,5.62,5.74,3715.19,3703.12,3703.12,2026-08-15,2024-03-11,IPCA,2024-04-02 21:26:34.052521
15/05/2029,11/03/2024,5.58,5.70,3209.03,3188.75,3188.75,2029-05-15,2024-03-11,IPCA,2024-04-02 21:26:34.052947
15/05/2045,11/03/2024,5.82,5.94,1289.32,1258.28,1258.28,2045-05-15,2024-03-11,IPCA,2024-04-02 21:26:34.053297
15/05/2035,11/03/2024,5.70,5.82,2291.66,2261.82,2261.82,2035-05-15,2024-03-11,IPCA,2024-04-02 21:26:34.053707
15/08/2024,11/03/2024,7.64,7.76,4109.80,4105.47,4105.47,2024-08-15,2024-03-11,IPCA,2024-04-02 21:26:34.054086
...,...,...,...,...,...,...,...,...,...,...
15/05/2019,23/09/2014,5.87,5.91,1892.55,1889.26,1888.53,2019-05-15,2014-09-23,IPCA,2024-04-02 21:26:39.855995
15/05/2015,23/09/2014,2.82,2.84,2418.30,2418.00,2417.36,2015-05-15,2014-09-23,IPCA,2024-04-02 21:26:39.856357
15/05/2035,22/09/2014,5.84,5.94,765.99,751.26,750.97,2035-05-15,2014-09-22,IPCA,2024-04-02 21:26:39.856727
15/08/2024,22/09/2014,5.80,5.88,1412.04,1401.57,1401.03,2024-08-15,2014-09-22,IPCA,2024-04-02 21:26:39.857094
15/05/2015,22/09/2014,2.80,2.82,2417.96,2417.66,2417.01,2015-05-15,2014-09-22,IPCA,2024-04-02 21:26:39.857460
15/05/2019,22/09/2014,5.73,5.77,1903.40,1900.08,1899.36,2019-05-15,2014-09-22,IPCA,2024-04-02 21:26:39.857757
15/05/2035,19/09/2014,5.87,5.97,761.14,746.50,746.02,2035-05-15,2014-09-19,IPCA,2024-04-02 21:26:39.858119
15/05/2019,19/09/2014,5.75,5.79,1900.76,1897.44,1896.24,2019-05-15,2014-09-19,IPCA,2024-04-02 21:26:39.858487
15/05/2015,19/09/2014,2.91,2.93,2415.32,2415.02,2413.75,2015-05-15,2014-09-19,IPCA,2024-04-02 21:26:39.858828
15/08/2024,19/09/2014,5.85,5.93,1404.76,1394.33,1393.44,2024-08-15,2014-09-19,IPCA,2024-04-02 21:26:39.859279

In [12]:
#frames = [prefixado, ipca]
#todos = pd.concat(frames)
ipca = ipca.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})
prefixado = prefixado.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})

In [13]:
ipca

,,CompraManha,VendaManha,PUCompraManha,PUVendaManha,PUBaseManha,Data_Vencimento,Data_Base,Tipo,dt_update
Data Vencimento,Data Base,,,,,,,,,
15/08/2024,12/03/2024,7.68,7.80,4112.61,4108.25,4108.25,2024-08-15,2024-03-12,IPCA,2024-04-02 21:26:34.045149
15/08/2026,12/03/2024,5.58,5.70,3721.46,3709.35,3709.35,2026-08-15,2024-03-12,IPCA,2024-04-02 21:26:34.050148
15/05/2045,12/03/2024,5.77,5.89,1303.22,1271.83,1271.83,2045-05-15,2024-03-12,IPCA,2024-04-02 21:26:34.051062
15/05/2029,12/03/2024,5.55,5.67,3216.18,3195.85,3195.85,2029-05-15,2024-03-12,IPCA,2024-04-02 21:26:34.051580
15/05/2035,12/03/2024,5.65,5.77,2305.51,2275.47,2275.47,2035-05-15,2024-03-12,IPCA,2024-04-02 21:26:34.052039
15/08/2026,11/03/2024,5.62,5.74,3715.19,3703.12,3703.12,2026-08-15,2024-03-11,IPCA,2024-04-02 21:26:34.052521
15/05/2029,11/03/2024,5.58,5.70,3209.03,3188.75,3188.75,2029-05-15,2024-03-11,IPCA,2024-04-02 21:26:34.052947
15/05/2045,11/03/2024,5.82,5.94,1289.32,1258.28,1258.28,2045-05-15,2024-03-11,IPCA,2024-04-02 21:26:34.053297
15/05/2035,11/03/2024,5.70,5.82,2291.66,2261.82,2261.82,2035-05-15,2024-03-11,IPCA,2024-04-02 21:26:34.053707
15/08/2024,11/03/2024,7.64,7.76,4109.80,4105.47,4105.47,2024-08-15,2024-03-11,IPCA,2024-04-02 21:26:34.054086
...,...,...,...,...,...,...,...,...,...,...
15/05/2019,23/09/2014,5.87,5.91,1892.55,1889.26,1888.53,2019-05-15,2014-09-23,IPCA,2024-04-02 21:26:39.855995
15/05/2015,23/09/2014,2.82,2.84,2418.30,2418.00,2417.36,2015-05-15,2014-09-23,IPCA,2024-04-02 21:26:39.856357
15/05/2035,22/09/2014,5.84,5.94,765.99,751.26,750.97,2035-05-15,2014-09-22,IPCA,2024-04-02 21:26:39.856727
15/08/2024,22/09/2014,5.80,5.88,1412.04,1401.57,1401.03,2024-08-15,2014-09-22,IPCA,2024-04-02 21:26:39.857094
15/05/2015,22/09/2014,2.80,2.82,2417.96,2417.66,2417.01,2015-05-15,2014-09-22,IPCA,2024-04-02 21:26:39.857460
15/05/2019,22/09/2014,5.73,5.77,1903.40,1900.08,1899.36,2019-05-15,2014-09-22,IPCA,2024-04-02 21:26:39.857757
15/05/2035,19/09/2014,5.87,5.97,761.14,746.50,746.02,2035-05-15,2014-09-19,IPCA,2024-04-02 21:26:39.858119
15/05/2019,19/09/2014,5.75,5.79,1900.76,1897.44,1896.24,2019-05-15,2014-09-19,IPCA,2024-04-02 21:26:39.858487
15/05/2015,19/09/2014,2.91,2.93,2415.32,2415.02,2413.75,2015-05-15,2014-09-19,IPCA,2024-04-02 21:26:39.858828
15/08/2024,19/09/2014,5.85,5.93,1404.76,1394.33,1393.44,2024-08-15,2014-09-19,IPCA,2024-04-02 21:26:39.859279

Grava os dados no Banco de Dados

In [17]:
connection_string = "postgresql://postgres:changeme@localhost:5432/postgres"

In [18]:
engine = create_engine(connection_string)

In [19]:
ipca.to_sql("dadostesouroipca", con=engine, if_exists="append", index=False)
prefixado.to_sql("dadostesouropre", con=engine, if_exists="append", index=False)

767